#!/bin/bash -x
#############################################################
# Prepare the system for cfengine, set up host as policyhost
# and as policy client for itself.
#############################################################

# First we set up some variables we need...
export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
iface=$(/sbin/route -n|/usr/bin/awk -v e='0.0.0.0' '{if(($1==e)&&($2!=e)){print $NF;}}'|/usr/bin/head -1)
ipaddr=$(/sbin/ifconfig ${iface}|/bin/grep 'inet addr:'|/usr/bin/cut -d: -f2|/usr/bin/awk '{ print $1}')
hostname=$(hostname)
grep $ipaddr /etc/hosts || echo "$ip `hostname --fqdn` `hostname`" >> /etc/hosts
grep $hostname /etc/hostname || echo ${HOST_NAME} > /etc/hostname
hostname ${HOST_NAME}

# Then we install cfengine and set it up to run for either RH or Debian
if [ -f /etc/redhat-release ];then
    export CFROOT=/var/cfengine
    yum update -y && yum install -y cfengine
    /etc/init.d/cfengine stop
    # more stuff needed here
elif [ -f /etc/debian_version ];then
    export CFROOT="/var/lib/cfengine2"
    dpkg -l | grep "^ii *cfengine2" || (/usr/bin/apt-get update && /usr/bin/apt-get install cfengine2)
    /etc/init.d/cfengine2 stop
    cp /etc/default/cfengine2 /etc/default/cfengine2.dist
    sed -e's/=0 *$/=1/' /etc/default/cfengine2.dist > /etc/default/cfengine2
    chmod 644 /etc/default/cfengine2
else
    echo "Cannot determine distribution or unsupported distribution";
    exit -1;
fi

# Then we copy our ppkey in order to authenticate self to self:
(cd ${CFROOT}/ppkeys; cp localhost.pub root-127.0.0.1.pub)
(cd ${CFROOT}/ppkeys; cp localhost.pub root-${ipaddr}.pub)

# Fetch our public git repository 
TMPDIR=$(mktemp -d /var/tmp/gitroot.XXXXX)
(cd ${TMPDIR} ;git clone git://github.com/fapestniegd/superstring.git)
rsync -avzPC --delete ${TMPDIR}/superstring/strings/cfengine/ ${CFROOT}/masterfiles/ > /dev/null 2>&1
/usr/bin/install -m 0744 ${CFROOT}/masterfiles/inputs/{update,cfservd,cfagent}.conf ${CFROOT}/inputs
/usr/bin/install -m 0744 ${CFROOT}/masterfiles/modules/module\:dynclass ${CFROOT}/modules
if [ -d "${TMPDIR}" -a "${TMPDIR}" != "/" ];then rm -fr ${TMPDIR}; fi

# Fire up cfengine, and get things going
/etc/init.d/cfengine2 start
/usr/sbin/cfexecd -F
/usr/sbin/cfexecd -F
/usr/sbin/cfagent -vKq
