#!/bin/bash
export PATH="/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
export LOG="/var/log/singularity.log"
log(){
    echo "$*" >> ${LOG}
touch /var/log/singularity.log
log "It worked!"
