#!/bin/bash
export PATH="/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
export LOG="/var/log/singularity.log"
log(){
    echo "$*" >> ${LOG}
}
touch /var/log/singularity.log
ec2_host=0
log "It worked!"

runscript(){
    script="$1"
    LENGTH=0; # github is giving me 0 byte replies...
    ATTEMPT=0
    while [ ${LENGTH} -eq 0 -a ${ATTEMPT} -lt 10 ]; do
        /usr/bin/wget -qO /tmp/${script} "${STRINGROOT}${script}?raw=true"
        LENGTH=$(/usr/bin/wc -l /tmp/${script}|/bin/sed -e's/ .*//g' -e's/^ *//g')
        ATTEMPT=`expr ${ATTEMPT} + 1`
        echo "script - ${script} (attempt ${ATTEMPT}) ${LENGTH} line reply."
    done
    chmod 755 /tmp/${script}
    /tmp/${script} > ${LOGDIR}/${script}.log 2>&1
}

# EC2
# come up with something better here plz:
public_hostname=$(wget -qO - http://169.254.169.254/latest/meta-data/public-hostname)
log "public_hostname: ${public_hostname}"
if [ ! -z ${public_hostname} ];then ec2_host=1; fi
if [ ${ec2_host} -ne 0 ];then
   runscript ec2-root-credentials 
   runscript ec2-user-data
fi
