#! /bin/bash

error=0 ; trap "error=$((error|1))" ERR

# Copy the keys to /boot and rewrite the crypttab
if [ -f $target/etc/crypttab ];then 
    for key in `awk '{print $3}' $target/etc/crypttab`; do
        if [ -f $key ];then
            /bin/cp $key $target/boot/
        fi
    done
    /bin/cp $target/etc/crypttab $target/etc/crypttab.bak
    sed -e 's/\/tmp\/fai/\/boot/' $target/etc/crypttab.bak > $target/etc/crypttab
    /bin/cp $target/etc/crypttab $target/boot
fi

# Create an initrd that will actually boot
TARGETVERSION=$(/bin/ls $target/lib/modules)
mkinitramfs -r $target -o $target/boot/initrd.img-${TARGETVERSION} ${TARGETVERSION}

exit $error
