#!/bin/sh

PREREQ="" 
prereqs(){         
    echo "$PREREQ" 
}

case $1 in 
    prereqs)         
        prereqs         
        exit 0         
    ;; 
esac

# Begin real processing below this line
[ ! -d ${DESTDIR}/boot ] && mkdir -p ${DESTDIR}/boot

# copy the crypttab into /boot on initrd
cp -p $target/boot/crypttab ${DESTDIR}/boot

# copy the keys referenced in the crypttab into /boot on initrd
for key in `/bin/cat /tmp/fai/crypttab|sed -e 's/#.*//g'|grep .|awk '{print $3}' 
if [ -f $target/${key} ];then
   cp -p $target/${key} ${DESTDIR}/boot
fi

exit 0 
