#!/bin/sh

PREREQ="" prereqs() 
{         
    echo "$PREREQ" 
}

case $1 in prereqs)         
    prereqs         
    exit 0         
    ;; 
esac

# Begin real processing below this line
[ ! -d ${DESTDIR}/boot ] && mkdir -p ${DESTDIR}/boot
cp -p /target/boot/crypttab ${DESTDIR}/boot
cp -p /target/boot/crypt_dev_sda2 ${DESTDIR}/boot

exit 0 
